//methods 
let fname = "Poojha M";
let lname = "Preetha";
let place = "Chennai";
let s1 = console.log("My name is "+fname+" "+lname+"."+"I am from "+place+".");
let s2 = console.log(`My name is ${fname} ${lname}.I am from ${place}.`);
console.log(fname.length);
console.log(fname.concat(lname));
console.log(fname.search("M"));
console.log(fname.toLowerCase());
console.log(fname.toUpperCase());
console.log(fname.toLocaleLowerCase());
console.log(fname.toLocaleUpperCase());
console.log(fname[3]);
console.log(fname.indexOf("a"));
console.log(fname.indexOf("o"));
console.log(fname.lastIndexOf("o"));
console.log(fname.split("o"));
console.log(fname.endsWith("M"));
console.log(fname.endsWith("p"));
console.log(fname.charAt("4"));
console.log(fname.charCodeAt(1));
console.log(fname.includes("M"));
console.log(fname.repeat(2));
console.log(fname.replace("M","Agastin"));
console.log(fname.slice(1,4));
console.log(fname.match(/ooj/g));
console.log(fname.localeCompare(lname));
console.log(fname.substr(0,3));
console.log(fname.substring(0,3));
console.log(fname.toString());
let hobby = " Playing ";
console.log(hobby.trim());
console.log(fname.valueOf());
